// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: proto/send.proto

package sendpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SendServiceClient is the client API for SendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendServiceClient interface {
	Send(ctx context.Context, opts ...grpc.CallOption) (SendService_SendClient, error)
}

type sendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSendServiceClient(cc grpc.ClientConnInterface) SendServiceClient {
	return &sendServiceClient{cc}
}

func (c *sendServiceClient) Send(ctx context.Context, opts ...grpc.CallOption) (SendService_SendClient, error) {
	stream, err := c.cc.NewStream(ctx, &SendService_ServiceDesc.Streams[0], "/proto.SendService/Send", opts...)
	if err != nil {
		return nil, err
	}
	x := &sendServiceSendClient{stream}
	return x, nil
}

type SendService_SendClient interface {
	Send(*SendRequest) error
	CloseAndRecv() (*SendResponse, error)
	grpc.ClientStream
}

type sendServiceSendClient struct {
	grpc.ClientStream
}

func (x *sendServiceSendClient) Send(m *SendRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sendServiceSendClient) CloseAndRecv() (*SendResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SendServiceServer is the server API for SendService service.
// All implementations must embed UnimplementedSendServiceServer
// for forward compatibility
type SendServiceServer interface {
	Send(SendService_SendServer) error
	mustEmbedUnimplementedSendServiceServer()
}

// UnimplementedSendServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSendServiceServer struct {
}

func (UnimplementedSendServiceServer) Send(SendService_SendServer) error {
	return status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedSendServiceServer) mustEmbedUnimplementedSendServiceServer() {}

// UnsafeSendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendServiceServer will
// result in compilation errors.
type UnsafeSendServiceServer interface {
	mustEmbedUnimplementedSendServiceServer()
}

func RegisterSendServiceServer(s grpc.ServiceRegistrar, srv SendServiceServer) {
	s.RegisterService(&SendService_ServiceDesc, srv)
}

func _SendService_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SendServiceServer).Send(&sendServiceSendServer{stream})
}

type SendService_SendServer interface {
	SendAndClose(*SendResponse) error
	Recv() (*SendRequest, error)
	grpc.ServerStream
}

type sendServiceSendServer struct {
	grpc.ServerStream
}

func (x *sendServiceSendServer) SendAndClose(m *SendResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sendServiceSendServer) Recv() (*SendRequest, error) {
	m := new(SendRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SendService_ServiceDesc is the grpc.ServiceDesc for SendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SendService",
	HandlerType: (*SendServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Send",
			Handler:       _SendService_Send_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/send.proto",
}
